ALTER TABLE "exercises" ADD COLUMN "primary_muscles" text[] DEFAULT '{}'::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "secondary_muscles" text[] DEFAULT '{}'::text[] NOT NULL;--> statement-breakpoint
-- Muscle groups for the starter exercises that trainers already have (new libraries get them on creation).
UPDATE "exercises" AS e
SET "primary_muscles" = v.p::text[], "secondary_muscles" = v.s::text[]
FROM (VALUES
  ('Squat', '{quadriceps,gluteal}', '{hamstring,adductor,lower-back}'),
  ('Goblet squat', '{quadriceps,gluteal}', '{hamstring,abs}'),
  ('Front squat', '{quadriceps}', '{gluteal,abs}'),
  ('Bulgarian split squat', '{quadriceps,gluteal}', '{hamstring,adductor}'),
  ('Lunge', '{quadriceps,gluteal}', '{hamstring,calves}'),
  ('Walking lunge', '{quadriceps,gluteal}', '{hamstring,calves}'),
  ('Leg press', '{quadriceps}', '{gluteal,hamstring}'),
  ('Leg extension', '{quadriceps}', '{}'),
  ('Leg curl', '{hamstring}', '{calves}'),
  ('Romanian deadlift', '{hamstring,gluteal}', '{lower-back}'),
  ('Step-up', '{quadriceps,gluteal}', '{hamstring,calves}'),
  ('Calf raise', '{calves}', '{}'),
  ('Wall sit', '{quadriceps}', '{gluteal}'),
  ('Hip thrust', '{gluteal}', '{hamstring}'),
  ('Glute bridge', '{gluteal}', '{hamstring,lower-back}'),
  ('Tek bacak glute bridge', '{gluteal}', '{hamstring,abs}'),
  ('Cable kickback', '{gluteal}', '{hamstring}'),
  ('Hip abduction', '{abductors}', '{gluteal}'),
  ('Clamshell', '{abductors}', '{gluteal}'),
  ('Donkey kick', '{gluteal}', '{hamstring}'),
  ('Bench press', '{chest}', '{triceps,front-deltoids}'),
  ('Incline dumbbell press', '{chest,front-deltoids}', '{triceps}'),
  ('Dumbbell fly', '{chest}', '{front-deltoids}'),
  ('Cable crossover', '{chest}', '{front-deltoids}'),
  ('Şınav', '{chest}', '{triceps,front-deltoids,abs}'),
  ('Diz üstü şınav', '{chest}', '{triceps,front-deltoids}'),
  ('Chest press makinesi', '{chest}', '{triceps,front-deltoids}'),
  ('Deadlift', '{hamstring,gluteal,lower-back}', '{quadriceps,trapezius,forearm}'),
  ('Barfiks', '{upper-back}', '{biceps,forearm}'),
  ('Lat pulldown', '{upper-back}', '{biceps}'),
  ('Seated cable row', '{upper-back}', '{biceps,back-deltoids}'),
  ('Dumbbell row', '{upper-back}', '{biceps,back-deltoids}'),
  ('Barbell row', '{upper-back}', '{biceps,lower-back,back-deltoids}'),
  ('Face pull', '{back-deltoids}', '{trapezius,upper-back}'),
  ('Back extension', '{lower-back}', '{gluteal,hamstring}'),
  ('Superman', '{lower-back}', '{gluteal}'),
  ('Overhead press', '{front-deltoids}', '{triceps,trapezius}'),
  ('Dumbbell shoulder press', '{front-deltoids}', '{triceps}'),
  ('Lateral raise', '{front-deltoids,back-deltoids}', '{trapezius}'),
  ('Front raise', '{front-deltoids}', '{}'),
  ('Rear delt fly', '{back-deltoids}', '{trapezius,upper-back}'),
  ('Arnold press', '{front-deltoids}', '{triceps}'),
  ('Biceps curl', '{biceps}', '{forearm}'),
  ('Hammer curl', '{biceps,forearm}', '{}'),
  ('Triceps pushdown', '{triceps}', '{}'),
  ('Overhead triceps extension', '{triceps}', '{}'),
  ('Dips', '{triceps,chest}', '{front-deltoids}'),
  ('Plank', '{abs}', '{obliques,front-deltoids}'),
  ('Yan plank', '{obliques}', '{abs,abductors}'),
  ('Dead bug', '{abs}', '{obliques}'),
  ('Bird dog', '{lower-back,abs}', '{gluteal}'),
  ('Crunch', '{abs}', '{}'),
  ('Bicycle crunch', '{abs,obliques}', '{}'),
  ('Russian twist', '{obliques}', '{abs}'),
  ('Mountain climber', '{abs}', '{front-deltoids,quadriceps}'),
  ('Hanging leg raise', '{abs}', '{forearm,obliques}'),
  ('Pallof press', '{obliques,abs}', '{}'),
  ('Koşu bandı', '{quadriceps,calves}', '{hamstring,gluteal}'),
  ('Bisiklet', '{quadriceps}', '{calves,hamstring}'),
  ('Kürek makinesi', '{upper-back,quadriceps}', '{biceps,hamstring}'),
  ('İp atlama', '{calves}', '{quadriceps}'),
  ('Burpee', '{quadriceps,chest}', '{abs,front-deltoids}'),
  ('Kettlebell swing', '{gluteal,hamstring}', '{lower-back,front-deltoids}'),
  ('Jumping jack', '{calves}', '{abductors,front-deltoids}'),
  ('Footwork', '{quadriceps,calves}', '{gluteal,hamstring}'),
  ('Hundred', '{abs}', '{front-deltoids}'),
  ('Frog', '{adductor}', '{gluteal,abs}'),
  ('Leg circles', '{adductor,abs}', '{abductors}'),
  ('Short spine', '{abs,hamstring}', '{lower-back}'),
  ('Elephant', '{abs,hamstring}', '{front-deltoids}'),
  ('Knee stretches', '{abs}', '{front-deltoids,quadriceps}'),
  ('Long stretch', '{abs,front-deltoids}', '{chest}'),
  ('Rowing', '{upper-back,back-deltoids}', '{biceps,abs}'),
  ('Side splits', '{adductor,abductors}', '{gluteal}'),
  ('Feet in straps', '{hamstring,adductor}', '{abs}'),
  ('Bridging', '{gluteal,hamstring}', '{lower-back}'),
  ('Roll up', '{abs}', '{}'),
  ('Single leg stretch', '{abs}', '{}'),
  ('Double leg stretch', '{abs}', '{}'),
  ('Spine stretch forward', '{hamstring,lower-back}', '{}'),
  ('Saw', '{obliques,hamstring}', '{upper-back}'),
  ('Swan', '{lower-back}', '{gluteal,upper-back}'),
  ('Swimming', '{lower-back,gluteal}', '{back-deltoids}'),
  ('Side kick series', '{abductors,gluteal}', '{obliques}'),
  ('Teaser', '{abs}', '{quadriceps}'),
  ('Rolling like a ball', '{abs}', '{}'),
  ('Hamstring esneme', '{hamstring}', '{}'),
  ('Kalça fleksör esneme', '{quadriceps}', '{}'),
  ('Göğüs açma', '{chest}', '{front-deltoids}'),
  ('Kedi-deve', '{lower-back,upper-back}', '{abs}'),
  ('Çocuk pozu', '{lower-back,upper-back}', '{}'),
  ('Thoracic rotation', '{upper-back,obliques}', '{}')
) AS v(name, p, s)
WHERE e."name" = v.name AND e."primary_muscles" = '{}' AND e."secondary_muscles" = '{}';
